# Exported from Render on 2026-07-14T04:58:52Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: SafetyDownloder
      runtime: node
      repo: https://github.com/AdityaGit121/SafetyDownloder
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
    - type: web
      name: secure-location-tracker
      runtime: node
      repo: https://github.com/AdityaGit121/secure-location-tracker
      plan: free
      envVars:
      - key: MONGO_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_ENV
        sync: false
      region: oregon
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
      rootDir: backend
